fix issue 902: chaosblade operator match containerId
chaosblade-io/chaosblade-operator pull request #210
Opened 2023-06-04 16:37 UTC by hengyoush

Remove unnessesary docker container id truncation

Fix issue: https://github.com/chaosblade-io/chaosblade/issues/902

2023-06-05 01:53 UTC, binbin0325 requested changes

2023-06-05 01:53 UTC, binbin0325 commented on exec/container/controller.go
> -				if containerRuntime == container.DockerRuntime {
It shouldn't be deleted

2023-06-05 01:53 UTC, binbin0325 commented on exec/container/controller.go
> -				if containerRuntime == container.DockerRuntime {
You just reverse the prefix matching
https://github.com/chaosblade-io/chaosblade-operator/blob/master/exec/container/controller.go#L164

2023-06-05 02:37 UTC, hengyoush commented on exec/container/controller.go
> -				if containerRuntime == container.DockerRuntime {
Oops, I have some misunderstanding about this.
I have fixed this issue, please check again.

2023-06-07 01:55 UTC, binbin0325 reviewed
You can combine commits into one, using git rebase

2023-06-07 01:55 UTC, binbin0325 commented on exec/container/controller.go
> +				containerRuntime, containerId = model.TruncateContainerObjectMetaUid(containerStatus.ContainerID)
No line feed required

2023-06-07 02:18 UTC, hengyoush commented on exec/container/controller.go
> +				containerRuntime, containerId = model.TruncateContainerObjectMetaUid(containerStatus.ContainerID)
done

2023-07-24 09:48 UTC, MandssS approved these changes

2023-07-24 09:49 UTC, merged